name: Trunk Analytics Uploader Wrapper
description: Wrapper that supplies defaults to the `analytics-uploader` action

inputs:
  token-staging:
    description: Organization token for staging.
    required: true
  token-prod:
    description: Organization token for prod.
  token-dev:
    description: Organization token for dev.
  token-dev2:
    description: Organization token for dev2.
  cli-version:
    description: stuff
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: true
  run:
    description: The command to run before uploading test results.
    required: false

runs:
  using: composite
  steps:
    - name: Upload test results
      continue-on-error: true
      uses: trunk-io/analytics-uploader@main
      with:
        org-slug: notests4
        token: ${{ inputs.token-staging }}
        junit-paths: ${{ inputs.junit-paths }}
        run: ${{ inputs.run }}
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
    - name: echo_context
      shell: bash
      run: echo ${{ toJson(steps) }}
