name: Clone Trunk Plugins

on:
  workflow_dispatch: {} # Allows manual triggering of the workflow
  schedule:
    - cron: 0 0 * * 0 # Run weekly on Sundays at midnight UTC

# Explicitly set permissions to minimum required
permissions:
  contents: read

jobs:
  clone-trunk-plugins:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout trunk-io/plugins repository
        uses: actions/checkout@v3
        with:
          repository: trunk-io/plugins
          path: trunk-plugins

      - name: List cloned repository contents
        run: ls -la trunk-plugins

      - name: Linter Tests
        # Run tests using KnownGoodVersion with any modified linters and conditionally all linters
        uses: ./.github/actions/linter_tests
